### ISSUE TITLE
What is the difference to https://github.com/FL550/dwd_weather?

### ISSUE THREAD

**Issue by sevorl** [hg1337/homeassistant-dwd#7]
What is the difference to https://github.com/FL550/dwd_weather?
What was the reason to build another component that seems very similar?

**Comment by hg1337** [comment]
The reason that both exist is mainly because the other one didn’t exist yet when I started this one, so they were more or less developed in parallel. I just added it to HACS much much later, because I don’t use HACS myself. And even had it running at some for some time, before I even put it on GitHub.

That‘s why when you look at the two integrations, they are quite different in their approach. For example, this one from the beginning on focused much on real measurements which are really good where I live, while the other one only uses forecast data on purpose. However, while this one supports „only“ on the official Weather Entity, the other one provides additional sensors. There are many other differences, best you try out both and decide for yourself, which one better fits your needs.

Because of the huge differences, it would be hard to unify the two, the outcome would probably rather be a third one. 😆 Or maybe both develop step by step in a similar direction and one gets obsolete eventually 🤷‍♂️

**Comment by sevorl** [comment]
Thanks for the detailed explanation. I live close to a weather station, so the actual values should be quite accurate. I will give it a try for sure!

**Comment by FL550** [comment]
Hi, I am the developer of the other mentioned integration. As you already said, I focused on the forecast data. The reason for this was, that the "real" measured values were published with at least an hour delay and I found the forecasted values quite accurate. Has this changed in the meantime? 

If yes, we should try to merge the two integrations, because I was also a bit confused what the differences between the two are.

**Comment by hg1337** [comment]
Hi @FL550,

the quality always depended a lot on the weather station, and I believe it still does. When I started my integration a few years ago, for my closest station the measurements were actually very good (more accurate than the forecast), so it was a no-brainer for me to use them. See e.g. this one, it has fresh measurements every hour:

https://opendata.dwd.de/weather/weather_reports/poi/10739-BEOB.csv

Originally, I even used the unofficial APIs of the official Warnwetter App but switched to the Open Data Server later. My observation is, that the measurement data that is available on the Open Data Server is exactly the same as for the Warnwetter App (the paid one that contains weather, not only warnings), except that they are a bit delayed, but always significantly les than one hour, and usually still better than the forecast for the currently hour for my favorite stations.

Strangely, one station got worse, it suddenly stopped providing the "present_weather" (sunny, rainy etc.), but the other measurement values still work perfectly. But the behavior for the Warnwetter App is exactly the same.

To get the best out of their individual station, I give the user the possibility to configure it:

![image](https://user-images.githubusercontent.com/76538974/234992320-6bcdb533-185b-4cd7-8510-602e318c1954.png)

And of course there are still many stations without measurement data, see https://github.com/hg1337/homeassistant-dwd/blob/main/stations.md. It's also shown in the setup dialog so the user can decide to use a closer station without measurements or one with measurements, but more far away.

![image](https://user-images.githubusercontent.com/76538974/234994472-8c680d76-ad54-44b4-afb0-f878cde3829e.png)

So the bottom line is basically, for me the measurements are very valuable and I wouldn't want to miss them, and except for a bit delay, they are exactly the same as for the official Warnwetter app. And each user can decide and configure for themselves what's better in their individual situation.

**Comment by hg1337** [comment]
Added to Q&A.
